### ISSUE TITLE
Correct way to handle NavigatorIOS?

### ISSUE THREAD

**Issue by swennemans** [Kureev/react-native-side-menu#10]
I was playing around with the package to use in combination with NavigatorIOS. I've got it to work, but I'm not 100% sure if this is the best practice. From the example it looks like you somehow pass NavigatorIOS as props to the menu. However, in my case the `<SideMenu/>` is the parent of `<NavigatorIOS/>` and therefore I use `this.refs` and call the function using `this.props`. Here is the gist: 
https://gist.github.com/swennemans/59f656f02497d0df6572

Do you take another approach? What is the benefit (besides your approach looks cleaner). 

Thanks :)

**Comment by Kureev** [comment]
Hm, imo looks pretty OK, as least I'd do something the same. Do you have any problems with it?
