### ISSUE TITLE
Experiment with new implementation for 2-side menus

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-side-menu#102]
@Kureev,
I have been experimenting with code and start implementing the 2 side menus. Unfortunately I ended up re-writing 75% of the code to support 2 menus feature. 

I want you to take a look at the example `TwoMenus` under examples folder.I have keep those that matter to me and dropped those that just polluted the code. 

What I'm thinking is maybe it's better to create a separate project called `react-native-2-side-menu` instead of put everything into a single project. in this way code can be a lot easier to maintain.

Any thoughts on that?

Here's the [code](https://github.com/alinz/react-native-side-menu/tree/two-side-menus/examples/TwoMenus)

**Comment by Kureev** [comment]
Sorry for that delay with review, @alinz. I'm on JSConf now, will do my best to review it ASAP

**Comment by alinz** [comment]
Any update for this example? Should I create a brand new project? or you think it can be some how merge in! It's complex! It might need your full weekend to do this. Let me know either way!

**Comment by Kureev** [comment]
I took a look on your proposal, but haven't enough time to write my feedback about it. In general, it's way more cleaner, than side-menu code, and implementation is good, **but** I think it should be a standalone project.

**Comment by alinz** [comment]
Thanks, I will create a separate project for that. I'd like to invite you as co-author since the initial code is based on your code. I will send the invitation once I create the project.

**Comment by Kureev** [comment]
@alinz sure, I would be glad to help. I think it's gonna be a good project! :+1:
