### ISSUE TITLE
Error: Cannot read property 'stopTracking' of undefined

### ISSUE THREAD

**Issue by mikedizon** [Kureev/react-native-side-menu#105]
Trying to toggle the side menu from another component (A "prev button" from react-native-navbar). This is the error I get.

Error: Cannot read property 'stopTracking' of undefined
 stack: 
  Object.maybeVectorAnim.start                     index.ios.bundle:42906
  Nav.openMenu                                     index.ios.bundle:53252
  Nav.toggleMenu                                   index.ios.bundle:53301
  Button.handlePress                               index.ios.bundle:53593
  React.createClass.touchableHandlePress           index.ios.bundle:41778
  TouchableMixin._performSideEffectsForTransition  index.ios.bundle:39501
  TouchableMixin._receiveSignal                    index.ios.bundle:39419
  TouchableMixin.touchableHandleResponderRelease   index.ios.bundle:39222
  executeDispatch                                  index.ios.bundle:15313
  forEachEventDispatch                             index.ios.bundle:15301
 URL: undefined
 line: undefined
 message: Cannot read property 'stopTracking' of undefined

**Comment by Kureev** [comment]
as I understood, `maybeVectorAnim` is a custom function you wrote? Can you share this function with us, please?

**Comment by mikedizon** [comment]
Here's the button.js I wrote

const SideMenu = require('react-native-side-menu');

import React, {
  StyleSheet,
  Component,
  Image,
  View,
  ScrollView,
  PixelRatio,
  Text,
  TouchableOpacity,
} from 'react-native';

import { connect } from 'react-redux/native';
import { toggle } from '../actions/slider';

const styles = StyleSheet.create({
  burgerButton: {
    width: 20,
    height: 21,
    left: 15,
    top: 30,
  },
});


export default class Button extends SideMenu {

  constructor(props, ctx) {
    super(props, ctx);
  }

  handleChange(isOpen) {
   if (!isOpen) {
     this.setState({
       touchToClose: false,
     });
   }
  }

  handlePress(e) {
    this.context.menuActions.toggle();
    if (this.props.onPress) {
      this.props.onPress(e);
    }
  }
  componentWillReceiveProps(props){
    const {touchToClose} = props;
    if(typeof touchToClose != 'undefined'){
      this.setState({
        touchToClose: true
      });
    }
  }

  render() {
    const {toggle, touchToClose} = this.props;
    return (
      <TouchableOpacity
        touchToClose={touchToClose}
        onChange={this.handleChange.bind(this)}
        onPress={this.handlePress.bind(this)}>
        <Image
          source={require('image!burger')}
          style={styles.burgerButton}
        />
      </TouchableOpacity>
    );
  }
}


Button.contextTypes = {
  menuActions: React.PropTypes.object.isRequired
};

It fails when it hits  this.context.menuActions.toggle(); in the handlePress function.


Here's where I render the Navigator

export default class Nav extends SideMenu {

  constructor(props, ctx) {
    super(props, ctx);
    this.state = {
      touchToClose: false,
    };
  }

  renderScene(route, navigator) {

    const Component = route.component;
    let navBar = route.navigationBar;
    if (navBar) {
      navBar = React.addons.cloneWithProps(navBar, { navigator, route, });
    }
    return (
      <View style={{ flex: 1, }}>
        {navBar}
        <Component navigator={navigator} route={route}
            touchToClose={this.touchToClose}
            toggle={this.toggle}
            />
      </View>
    );
  }

  render() {
    const { toggle, open, close, touchToClose } = this.props;
    return (
      <Navigator
        toggle={toggle}
        renderScene={this.renderScene}
        touchToClose={touchToClose}
        initialRoute={{
          component: Slider,
          navigationBar: (
            <NavigationBar
              customTitle={<CustomTitle/>}
              customPrev={<Button
                touchToClose={touchToClose}
                onPress={toggle}
                toggle={toggle}/>}
              customNext={<SearchButton/>}
              style={styles.navigator}/>
          ),
        }}
      />
    );
  }
}

**Comment by mikedizon** [comment]
I should probably add that I am using redux and react-native-navbar. I have an action that defines toggle

**Comment by Kureev** [comment]
@mikedizon can you tell me about which `this.toggle` you're talking about in `Nav` class here:
```jsx
<View style={{ flex: 1, }}>
    {navBar}
    <Component navigator={navigator} route={route}
        touchToClose={this.touchToClose}
        toggle={this.toggle} />
</View>
```

**Comment by mikedizon** [comment]
```javascript
import * as types from './actionTypes';

export function toggle() {
  return {
    type: types.TOGGLE
  };
}
```

**Comment by mikedizon** [comment]
Which is set at

```javascript
<Navigator
        toggle={toggle}/>
```

I added it again at __NavigationBar__ while playing around.

**Comment by mikedizon** [comment]
Here's the contents to my slider.js

I should note that the Button here does work. It does not work when called from the navbar.

I can confirm that the functions in the actions and reducers are being called.

```javascript
class Button extends Component {
  handlePress(e) {
    this.context.menuActions.toggle();
    if (this.props.onPress) {
      this.props.onPress(e);
    }
  }

  render() {
    return (
      <TouchableOpacity
        onPress={this.handlePress.bind(this)}>
        <Text style={this.props.style}>{this.props.children}</Text>
      </TouchableOpacity>
    );
  }
}

Button.contextTypes = {
  menuActions: React.PropTypes.object.isRequired
};

export default class Slider extends SideMenu {
  constructor(props, ctx) {
    super(props, ctx);
    this.state = {
       touchToClose: false,
     };
  }

  componentWillReceiveProps(props){
    const {touchToClose} = props;
    if(typeof touchToClose != 'undefined'){
      this.setState({
        touchToClose: true
      });
    }
  }


  handleChange(isOpen) {
   if (!isOpen) {
     this.setState({
       touchToClose: false,
     });
   }
  }

  handleOpenWithTouchToClose() {
    this.setState({
      touchToClose: true,
    });
  }

  render() {
    const {touchToClose, toggle} = this.props;
    return (
      <SideMenu
        menu={<Menu />}
        touchToClose={this.state.touchToClose}
        onChange={this.handleChange.bind(this)}>
        <View style={styles.container}>
          <Text style={styles.welcome}>
            Welcome to React Native!
          </Text>
          <Text style={styles.instructions}>
            To get started, edit index.ios.js
          </Text>
          <Text style={styles.instructions}>
            Press Cmd+R to reload,{'\n'}
            Cmd+Control+Z for dev menu
          </Text>
          <Button style={styles.button2}
            onPress={toggle}>
            Open menu (Overlay Closes)
          </Button>
        </View>
      </SideMenu>
    );
  }
}

Slider.contextTypes = {
  menuActions: React.PropTypes.object.isRequired
};
```

**Comment by mikedizon** [comment]
onPress={toggle} in the SideMenu is probably unnecessary.

**Comment by mikedizon** [comment]
@alinz @Kureev what are u thinking?

**Comment by alinz** [comment]
@mikedizon, do you think this issue can be closed because I have provided an example in this issue #97?

**Comment by mikedizon** [comment]
Thank u so much!
