### ISSUE TITLE
How can I disable Side Menu effect on the left side and just enable the effect on the right side?

### ISSUE THREAD

**Issue by heyuan2816** [Kureev/react-native-side-menu#106]
Hi Kureev, thank you very much for sharing this side menu component, very helpful. And I have a question on how to use it.

So I try to enable the side menu effect on the right side as below and it works:

        <SideMenu menu={<MySideMenu nav={this} />} menuPosition='right'>
          <NavigatorIOS ref="navigator" style={styles.container} initialRoute={{
            component: PostRequest,
            title: I18n.t('search'),
            rightButtonTitle: I18n.t('menu'),
            onRightButtonPress: this.showSideMenu,
            passProps: { user: user },
          }} />
        </SideMenu>

However, when I slide from left to right, the side menu effect also shows up (the screen moves from left to right as my finger moves from left to right), which I don't want. Any idea how can I disable that?

Thanks,
Francis

**Comment by Kureev** [comment]
Sure you use latest version?

**Comment by heyuan2816** [comment]
I think so. But what is the latest version?
And I just tried npm update again, but the problem remains.
Any idea

**Comment by Kureev** [comment]
Could it be related to https://github.com/Kureev/react-native-side-menu/pull/103 ?
