### ISSUE TITLE
Managing menu state

### ISSUE THREAD

**Issue by pangers** [Kureev/react-native-side-menu#109]
I was wondering how to manage state in the same class as the one rendering <SideMenu>? I've been trying to set the contextTypes but I just cant seem to get it.

Here is some example code:

    class SideBar extends Component {
	render() {
		var menu = <Menu onPress={this.replaceWithNewScene.bind(this)}/>;
		return (
			<SideMenu
				menu={menu}
				touchToClose={true}>
				<Navigator 
					ref="baseNavigator"
			        initialRoute={{
			          id: 'landingPage'
			          }}
			        style={styles.navigator}
			        renderScene={this.renderScene}
			        configureScene={this.configureScene}/>
			</SideMenu>
		);
	}

        ....implement renderScene and configureScene here

        replaceWithNewScene(id) {
  		this.refs.baseNavigator.replace({ 
  			id: id 
  		});
            this.context.menuActions.close();
  	    }
    }

    SideBar.contextTypes = {
      menuActions: React.PropTypes.object.isRequired
    };

I get an undefined is not an object (evaluating 'this.context.menuActions.close')
Where am I going wrong?

**Comment by Kureev** [comment]
You can't access context from the parent component. If you want parent component reflect changes from the child components, you should use one of the data-flow technics, for example use redux (or any other flux implementation) and bind your component to store changes.

**Comment by pangers** [comment]
I see.. how could I go about closing the side bar when I have made a selection in the menu? Does my Menu component have access to the context?

**Comment by Kureev** [comment]
Your menu has an access to `context`, because it would be a child of `SideMenu` component:
```
SideMenu
  |-- Menu
  |-- ContentView
```

**Comment by Kureev** [comment]
So, @pangers, have you managed to solve this issue?

**Comment by pangers** [comment]
@Kureev Yes, all clear now!

**Comment by Maxyss** [comment]
Hey @pangers 
How did you solve your issue? I have the same...

**Comment by pangers** [comment]
@Maxyss Yes, whenever you access the context to close or open the side menu, you must do so from a child component of the <SideMenu> component.

**Comment by Maxyss** [comment]
@pangers could you share code please?

**Comment by pangers** [comment]
@Maxyss When I wrote my previous comment, I didn't realise the API for React Native Side Menu had changed. It looks like you can open or close the side menu with just a prop as shown in the documentation.
