### ISSUE TITLE
When subview has a <TouchableOpacity/>, the side menu has not any response?

### ISSUE THREAD

**Issue by ele828** [Kureev/react-native-side-menu#11]
When subview has a TouchableOpacity properties, the side menu has not any response?

so that I can not move the Side Menu out... Is that responser conflict to subview's properties?

Here is my project if you need:

https://github.com/leanote/leanote-ios

Thanks a lot :)

**Comment by ele828** [comment]
![](http://i1.tietuku.com/e64d481d5919f571.png)

**Comment by Kureev** [comment]
Can you confirm that `0.2.5` doesn't solve this issue and it's not related to #4 ?

**Comment by ele828** [comment]
@Kureev  Yeah, solve it thanks
