### ISSUE TITLE
DisableGestures on specific pages

### ISSUE THREAD

**Issue by JoaoCnh** [Kureev/react-native-side-menu#111]
I have a menu on a navbar that when you click it, it opens the side menu. And you can also open it by swiping on the left just like in the example.

But I want that the gesture (swiping left) on some pages just pops() the stack and it goes back. To do this I would have to disable the gestures on the SideMenu. Any ideas on how I can achieve this on certain views?

**Comment by Kureev** [comment]
Hm, sounds like a nice feature!

**Comment by alinz** [comment]
I think this is too specific to put into the project as a feature. I think this needs to be handle by you, @JoaoCnh. However, I want to see your implementation as well. Would you please create a simple code.

**Comment by Kureev** [comment]
I'm going to export gesture hooks, @alinz :wink:

**Comment by ilanasufrin** [comment]
@Kureev do you know of anybody who has successfully achieved the behavior that @JoaoCnh described? I'd also like to disable swiping on certain pages

**Comment by alinz** [comment]
@ilanasufrin I have done it. There are so many ways to achieve this behavioural. Here are the two most common ones:

1: Without out any 3rd library:
   -  create a method call `disableGesture` in a component which wraps `SideMenu`. 
   -  pass that function all the way down to all children.
   -  if any of those children wanted to disable gesture, they call the function.
   -  `disableGesture` is as follows:

```js
disableGesture(value) {
   this.setState({
      gesture: value
   });
}
```

and  in your render function you just pass the state.gesture to gesture props.

2: second approach is a lot cleaner and I hope you have used it in your current app. if you don't, please start using flux like framework such as redux or reflux. You have to separate all business logic from UI as much as possible to make everything simpler.

If you need an example, I can make one for you.

Cheers.

**Comment by JoaoCnh** [comment]
@alinz Thx I'll definitely try this today and give some feedback

**Comment by Kureev** [comment]
btw, I've investigated this a little bit more and can say that if we're talking about `Navigator`, then we can't override default behavior

**Comment by ilanasufrin** [comment]
@alinz you're right, I ended up doing it with a state that I set based on the component 
```
disableGestures={this.state.menuShouldNotOpen}
```

**Comment by alinz** [comment]
@ilanasufrin nice! :+1:

**Comment by alinz** [comment]
@Kureev I think this ticket can be closed now!

**Comment by akshaysinghi** [comment]
use react native simple events.. simple solution

**Comment by alinz** [comment]
@akshaysinghi this approach is not my favourite because once it's been used, the traceability of event will be lost. What I mean is once the application becomes very large, it becomes very hard to find who's firing that event.

what I usually do is either encapsulate that event inside that component and I don't leak it out side or use flux-like system such as redux to maintain my actions.
