### ISSUE TITLE
Setting default open possible?

### ISSUE THREAD

**Issue by JoaoCnh** [Kureev/react-native-side-menu#114]
I'm trying to put the sidemenu opened by default. I can't seem to find anything in the docs or code that would allow me to do that. Is there any way at all?

**Comment by Kureev** [comment]
Nope, nobody asked for this so far. But I think it's a nice feature :+1:

**Comment by alinz** [comment]
@JoaoCnh, I think you can get this to work by just call openMenu in your menu's `componentDidMount`, until either you or @Kureev implement this feature.

if openMenu didn't open the sideMenu, wrap it with `setTimeout` and set the timeout to 0. I know this is a hack but at least it gets you going.

**Comment by Kureev** [comment]
Released in `0.15`.
