### ISSUE TITLE
How to navigate to a view from the side menu?

### ISSUE THREAD

**Issue by Thorbenandresen** [Kureev/react-native-side-menu#116]
Hi,

does anyone have an example with a working menu navigation in place? I.e. that when you touch on "About" or "Contact" in the Side Menu, it would navigate to the respective page in the main view? 

Thank you!

**Comment by Kureev** [comment]
Probably, you can find answer here: https://github.com/alinz/example-side-menu-redux
@alinz

**Comment by Thorbenandresen** [comment]
Thank you - I am wondering if the is also a plain vanilla React solution without Flux, Redux & Co.

**Comment by Thorbenandresen** [comment]
This here is awesome: https://github.com/mcnamee/react-native-starter-app
