### ISSUE TITLE
How can I openMenu by press an Button?

### ISSUE THREAD

**Issue by RockyF** [Kureev/react-native-side-menu#117]

**Comment by Kureev** [comment]
Yes, you should use `menuActions` context object. Take a look on README for further explanations.

**Comment by RockyF** [comment]
I was trying to openMenu through a button in an external container instead of inside the SideMenu.

**Comment by Kureev** [comment]
The only one way to open a menu in this case is to emit some kind of event/action/whatever, hook it up from one of child components and use `menuActions` as I've described above.

**Comment by RockyF** [comment]
Thanks!
