### ISSUE TITLE
menuDirection right causes content to clip

### ISSUE THREAD

**Issue by jaysson** [Kureev/react-native-side-menu#119]
Text does not appear if menu is on right side.
![simulator screen shot 23-oct-2015 11 04 51 pm](https://cloud.githubusercontent.com/assets/1563862/10700351/d1707238-79da-11e5-8adb-eac4cf3f7d82.png)
![simulator screen shot 23-oct-2015 11 03 37 pm](https://cloud.githubusercontent.com/assets/1563862/10700359/de0a7804-79da-11e5-89b2-be3be7f84304.png)

I think the menu is 100% wide, and gets hidden behind content view. However, if I try to reduce the width of menu, I get whitespace there.
![simulator screen shot 23-oct-2015 11 08 23 pm](https://cloud.githubusercontent.com/assets/1563862/10700379/01036f1e-79db-11e5-8461-685359933419.png)

How to properly implement a right sidebar?

**Comment by Kureev** [comment]
Ok, there are a few options there. First of all - your text is fine, but it lays under the "content" view. 
So, first two things comes to my mind:
- Use padding
- Change alignment to the right

Let me know if that helped you.

**Comment by Kureev** [comment]
Closed due to lack of feedback
