### ISSUE TITLE
ScrollView and ListView don't scroll with 0.2.4.  Version 0.2.3 does work. 

### ISSUE THREAD

**Issue by swennemans** [Kureev/react-native-side-menu#12]
I'm trying to implement a Scrollview or Listview in either a NavigatorIOS or regular Navigator component. In 0.2.4 this doesn't work. In 0.2.3 it does work. Related to: https://github.com/Kureev/react-native-side-menu/issues/4

Here is a gist: 
https://gist.github.com/swennemans/2cbfce22c388e7b8132d

**Comment by Kureev** [comment]
Yep, it's known issue, check 0.2.5. Looking forward for your feedback.
