### ISSUE TITLE
Is it possible to limit swipeable area to first 40 pixels?

### ISSUE THREAD

**Issue by NoelBaron** [Kureev/react-native-side-menu#122]
By default, the entire component view is swipeable. Have you exposed a property that would allow us to enable swipe/drag only when the user drags from the very-most left side of the view?

**Comment by Kureev** [comment]
Yes. You can take a look on (component's API)[https://github.com/Kureev/react-native-side-menu#component-props], but I think you're looking for `toleranceX`.
