### ISSUE TITLE
menuActions outside of the scope?

### ISSUE THREAD

**Issue by PatrickHeneise** [Kureev/react-native-side-menu#15]
I'm trying to add a navbar with a button that should toggle the menu, but can't find where menuActions are exposed.

I tried various ideas with this.toggleMenu and having `toggleMenu` as a function in the menu class, but don't get it to work.

Any ideas?

```
    var menu = <Menu navigator={nav}/>;

    return (
      <View>
        <View>
          <TouchableOpacity onPress={() => menu.toggleMenu()}>
            <Text>Click</Text>
          </TouchableOpacity>
          <View>
            <Text>
              MyApp
            </Text>
          </View>
        </View>
        <SideMenu menu={menu}>
          <ItemView navigator={nav} />
        </SideMenu>
      </View>
    );
```

**Comment by Kureev** [comment]
I don't see any way to expose this functionality outside of `SideMenu` component. It can't be a static method as far as it use state to store current menu state. Why do you have this case? I mean isn't it enough to have an access to it in `Menu` component via prop?

**Comment by PatrickHeneise** [comment]
It's a header/navbar outside of the sidebar and I don't want it to be pushed to the side like the content.

**Comment by Kureev** [comment]
But if you have content outside of the `SideMenu`, it's not gonna work: when you open/close menu, it move only the layer inside. It'll looks like your navbar has `position: fixed`.

**Comment by PatrickHeneise** [comment]
The content is within SideMenu. It's just one button (hamburger icon) which is in the header to open/close the SideMenu.

**Comment by Kureev** [comment]
Okay, the only 1 think I can do for you (and what actually I've made in `5.1` version) - is to pass props to the first-level children. I'd like to set up `context`, but it works weird now, so I'd like not to relay on it. On first-level components you can use `this.props.menuActions` to access API. Does it solve your request?

**Comment by PatrickHeneise** [comment]
Yes, that should work. If menuActions are exposed there are lots of possibilities to control the menu. Thanks!

**Comment by Kureev** [comment]
You're welcome!
