### ISSUE TITLE
Issue with scrolling a ListView when used with a side menu.

### ISSUE THREAD

**Issue by holoed** [Kureev/react-native-side-menu#16]
I made the following change in my app to get the scrolling to be smooth in the main list view. Otherwise it would periodically get stuck because of horizontal movements of the side menu.

```javascript
handleMoveShouldSetPanResponder: function(e: Object, gestureState: Object) {
    var x = Math.round(Math.abs(gestureState.dx));
    var y = Math.round(Math.abs(gestureState.dy));

    if (x > 10 && y < 10) {
      return true;
    }
    return false;
  },
```

**Comment by Kureev** [comment]
I think adding tolerance option could be a nice solution for cases like this one

**Comment by Kureev** [comment]
Added `toleranceX` and `toleranceY` props to component. Version bumped to `0.4.0` :wink:
