### ISSUE TITLE
Error trying the menu in an empty app

### ISSUE THREAD

**Issue by borillo** [Kureev/react-native-side-menu#2]
Hi,

Thanks a lot for sharing this component!!
Maybe i'm doing something wrong, but i can't incorporate the menu in an empty react-native app :(

Code:
https://gist.github.com/borillo/705123948e706c55c9fe

Running app output:
![captura de pantalla 2015-04-07 a las 21 02 28](https://cloud.githubusercontent.com/assets/570960/7031133/9eb9b218-dd69-11e4-8357-48c9479bc701.png)

Thanks a lot in advance!!

**Comment by borillo** [comment]
Also my package.json:

{
  "name": "catalogo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "^0.3.4",
    "react-native-side-menu": "^0.2.0"
  }
}

**Comment by Kureev** [comment]
I think the problem is in `MenuItem` and `Caption` components. It's my custom components, and they're not distributed in RN by default. I recommend you just replace `MenuItem` and `Caption` components with something else. For example:
```javascript
var Menu = React.createClass({
  about: function() {
    this.props.menuActions.close();
  },
 
  render: function() {
    return (
      <View>
        <Text>Menu</Text>
        <Text onPress={this.about}>About</Text>
      </View>
    );
  }
});
```

**Comment by borillo** [comment]
Completly right :(
I thought they were RH components, sorry.

I'm working in a set of short videos about RH and i would like to include you menu, so let me know if you want some help creating or documenting those examples.

Thx again

**Comment by Kureev** [comment]
@borillo 
I'm glad, that it solved your issue!
Yeah, any contribution will be perfect! As far as my English isn't that good, it can help a lot with example descriptions!

**Comment by Kureev** [comment]
@borillo I added "examples" folder. It would be nice, if you can find some time to check it out :)
