### ISSUE TITLE
Add onChange callback

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-side-menu#23]
Is there any way SideMenu can update the content whether it's opened or closed?
For example, I need to do something as soon as the SideMenu opens. Any suggestion?

**Comment by Kureev** [comment]
In your suggested implementation you'll invoke `onChange` even if you don't change current state (i.e. menu is open and after swipe menu is still open.

**Comment by alinz** [comment]
hmm, `SideMenu` calls `onChange` method. It's just a receiver.

**Comment by Kureev** [comment]
Yeah, I mean that it calls `onChange` even when the state haven't been changed.

**Comment by alinz** [comment]
I clearly see the issue. nice catch. I have added `prevState` variable and `isChanged` method which fixes this issue. ddc0253ea3373de66abf4c14b00d41ca81c075b9

**Comment by Kureev** [comment]
Gonna be solved in #24
