### ISSUE TITLE
Issue of having ScrollView as content

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-side-menu#26]
If you have a `ScrollView` as content of `SlideMenu`, `toleranceX` and `toleranceY` are not helping with the current implementation. After digging, I realize that [this line](https://github.com/Kureev/react-native-side-menu/blob/v0.5.4/index.js#L114), `return x != this.props.toleranceX && y < this.props.toleranceY;` needs to be changed to `return x > this.props.toleranceX && y < this.props.toleranceY;` in order for them to work properly.

Does it make sense?

**Comment by Kureev** [comment]
Seems so
