### ISSUE TITLE
Unsupported layout animation createConfig property (null)

### ISSUE THREAD

**Issue by bright-sea** [Kureev/react-native-side-menu#28]
In linear animation mise to set property: LayoutAnimation.Properties.opacity,  see 
https://github.com/facebook/react-native/issues/1135#issuecomment-98903335

Here is code in Animation.js:

<pre>
   linear: {
      duration: 300,
      create: {
        type: LayoutAnimation.Types.linear,
      },
      update: {
        type: LayoutAnimation.Types.linear,
        springDamping: 0.7,
      },
    },
</pre>

It should be:

<pre>
   linear: {
      duration: 300,
      create: {
        type: LayoutAnimation.Types.linear,
        property: LayoutAnimation.Properties.opacity,
      },
      update: {
        type: LayoutAnimation.Types.linear,
        springDamping: 0.7,
        property: LayoutAnimation.Properties.opacity,
      },
    },
</pre>

**Comment by piyushchauhan2011** [comment]
Thanks @bright-sea, my issue of createConfig error is resolved with the following code.

**Comment by Kureev** [comment]
PR has been merged (https://github.com/Kureev/react-native-side-menu/pull/29)

**Comment by GiantGit15** [comment]
Hi All.
I am learning React-Native now.
I was going to make side menu.
So I have done it using guide by Kureev.
But the execution is out.
Could you please help me?

**Comment by Kureev** [comment]
Hi @GiantGit15! Please, create a new issue and attach logs/screenshots to give us more insights about your bug.

**Comment by idibidiart** [comment]
<img width="375" alt="screen shot 2015-10-14 at 10 35 36 am" src="https://cloud.githubusercontent.com/assets/1288823/10492186/5cdbb536-725f-11e5-9a17-04d14b080384.png">

I'm seeing it again when running another app in simulator then going back to the RN app that was already running.

**Comment by idibidiart** [comment]
@Kureev  can you please re-open?
