### ISSUE TITLE
Issue with ScrollView after react-native-side-menu installation.

### ISSUE THREAD

**Issue by piyushchauhan2011** [Kureev/react-native-side-menu#30]
I've installed the `react-native-side-menu` package and it blocks the scrollview for some reason. When I remove the sidemenu, my ListView and ScrollView works as expected. I don't know why is this happening. A simple example could be made by installing the react-native-side-menu and using ListView as sample component or ScrollView with many Text components. It could be seen that UI will have scrolling issues.

**Comment by alinz** [comment]
@piyushchauhan2011, Try to apply my patch and see if this actually fixes your problem.

**Comment by Kureev** [comment]
Yeah, please, let me know if it works for you

**Comment by Kureev** [comment]
@alinz Thanks for the patch!

**Comment by piyushchauhan2011** [comment]
Hey @alinz I tried on the app for my startup ["Docit"](http://getdocit.com/) and its working good. Heaps of thanks mate!

**Comment by alinz** [comment]
Glad to help! :)
