### ISSUE TITLE
Syntax error introduced in 0.7.0

### ISSUE THREAD

**Issue by Benmidi** [Kureev/react-native-side-menu#33]
First, thanks for making this great side panel. By far the smoothest animation of all the implementations I've tried! Plus, it does a great job of canceling other events while panning.

I noticed in the latest version there's a typo that causes my apps to crash. It's just a wayward semicolon.

https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L194

**Comment by Kureev** [comment]
Thanks for nice catch! Fixed in `0.7.1`!
