### ISSUE TITLE
set frontView backgroundColor to transparent?

### ISSUE THREAD

**Issue by Benmidi** [Kureev/react-native-side-menu#34]
In some of my apps I'm using a <LinearGradient> to apply background color to the "main content" but this style(https://github.com/Kureev/react-native-side-menu/blob/master/styles.js#L26) overrides that tag.
When I set the backgroundColor to transparent on frontView I'm able to use the LinearGradient correctly.

**Comment by Kureev** [comment]
Fixed in gh repo, next release will contain that it.
