### ISSUE TITLE
When using SideMenu, the ScrollView do not work

### ISSUE THREAD

**Issue by mengwei607** [Kureev/react-native-side-menu#4]
```
<SideMenu menu={menu}>
  <Listview ...>
</SideMenu>
```

Look at the source code, onStartShouldSetPanResponder is true,  so maybe scrollview cover.

Do not know how to solve the problem?

**Comment by chirag04** [comment]
Interesting. 

@Kureev  This will be a tough problem to solve. ``onStartShouldSetPanResponder`` will not give scrollview a chance to scroll Unless we check if its a horizontal or vertical scroll.

**Comment by chirag04** [comment]
@Kureev I think https://github.com/t4t5/react-native-router/blob/master/index.js#L62-L71 can help us.

what do you think?

**Comment by chirag04** [comment]
sweet! can you bump the version? Also, would you have time to document the openMenu externally.

It's been great working with you :)

**Comment by Kureev** [comment]
Done! 0.2.3 has been released!

**Comment by qingfeng** [comment]
:beer:

**Comment by chirag04** [comment]
Cheers! :beer:

**Comment by Kureev** [comment]
:beer:

**Comment by mengwei607** [comment]
:beer:

**Comment by Kureev** [comment]
I'm gonna to revert this commit. It should be done different way.

**Comment by Kureev** [comment]
I've updated an example in `v0.2.4`, so feel free to update your package and check an example with ScrollView + Navbar.

**Comment by chirag04** [comment]
Kureev i added that because listView scroll was not working.

**Comment by Kureev** [comment]
Please, check 0.2.5. Looking forward for your feedback.
