### ISSUE TITLE
InteractionManager Warning message

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-side-menu#40]
If you drag the menu and keep your finger on the screen, `react-native` throw a warning as below

![screen shot 2015-06-03 at 11 12 37 am](https://cloud.githubusercontent.com/assets/967050/7963639/bc00fa08-09e1-11e5-9ea4-3b5e305ed193.png)

Are you guys getting the same warning? Any suggestion? I think 2 seconds for slide is a little bit too low.

**Comment by Kureev** [comment]
I guess it's just a warning and we can ignore it, but I don't get why?

**Comment by alinz** [comment]
I will close this one until I find a proper solution. As you mentioned, for now it is ok to ignore it.
