### ISSUE TITLE
git clone permissions error

### ISSUE THREAD

**Issue by chumster** [Kureev/react-native-side-menu#43]
In this README.md:
https://github.com/Kureev/react-native-side-menu/blob/master/examples/simple/README.md

this doesn't work for me due to lack of permissions:
"First of all, clone repo to your computer
$ git clone git@github.com:Kureev/react-native-side-menu.git"

*****

this works for me:
git clone https://github.com/Kureev/react-native-side-menu.git

**Comment by alinz** [comment]
@chumster if you have not set your ssh key (public and private) in your terminal, you **can not** use `git clone git@github.com:Kureev/react-native-side-menu.git`.

@Kureev I think we should change the README to `clone the project` and let the user decide whether he/she want's to clone it with ssh or normal https.

**Comment by Kureev** [comment]
Thanks for catch! :+1: 
@alinz Yeah, you're right, fixed.
