### ISSUE TITLE
Have Navbar button control menuAction methods?

### ISSUE THREAD

**Issue by achang28** [Kureev/react-native-side-menu#44]
On a given scene, how can the menuAction methods be utilized from one of the bar buttons on the top nav bar?

Naturally, I am setting up the navbar buttons in the previous (from where I intend on using the react-native-side-menu).  For example, I include the "onRightButtonPress()" function as a parameter when using "this.props.navigator.push()' function in the previous scene.

**Comment by alinz** [comment]
@albertwchang For simple and small project you can keep passing the ref to menuActions to your child components. I wouldn't recommend of doing this for mid or larger project. You should use flux, reflux or any system that decouple these actions. if you nee more help I can provide you a simple example.

p.s. I've been using refluxjs heavily in one big project contains 30 scenes and lots of animations. It's worth investing to those kind of frameworks.

**Comment by kevtastic** [comment]
@alinz 
how did you pass menuactions? the only way i see passing it right now is through menu, but there must be a way to also pass it to the child of sidemenu.

**Comment by alinz** [comment]
Sorry for long delay, @kevtastic, I've been busy with stuff. :D
So SideMenu component injects `menuActions` object automatically to all its own direct children. [Here](https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L247-L251)'s the code for that. So inside your child component you can access `menuActions` by using `this.props.menuActions`.

From that moment you can keep passing menuActions down to child's children components using the following code.

```js
render () {
    var props = this.props;
    return (
        <MyAwesomeChild menuActions={props.menuActions}/>
    );
}
```

Or using es7 spread feature like this:

```js
render () {
    var props = this.props;
    return (
        <MyAwesomeChild {...props}/>
    );
}
```

I might be wrong but based on my experience, I don't like to pass these actions down to hierarchy of children. I usually use `flux`, `reflux` architectures for doing these type of systems. But again it's your choice! :P Remember, we are still finding a lot of good patterns for writing apps using React.

**Comment by kevtastic** [comment]
oh awesome! I actually moved the event I was worried about to flux in the mean time but this is super helpful regardless!

**Comment by kevtastic** [comment]
Actually I have one more issue if you have the time. I'm actually trying to pass menuactions into the firstroute.

**Comment by Kureev** [comment]
@kevtastic Not sure I got your second question about passing `menuActions` into initial route, but if I got it correct, you need to use `this.props.menuActions` in the first-level children. Like if you have 
```javascript
class SomeComponent extends Component
```
as a content-view /menu-view, and something inside it should use `menuActions`, you can just access them via `this.props.menuActions` but it works *only for first-level children*. I'll try to move it to context ASAP, mb @alinz would be also interested in that.
