### ISSUE TITLE
Any way to restrict menu opening to a certain point away from the screen edge?

### ISSUE THREAD

**Issue by marcshilling** [Kureev/react-native-side-menu#47]
I have a view with a horizontal `ScrollView` in it and I find myself accidentally opening the menu too often. I've played around with the `toleranceX` prop a little bit, and this does help - but not completely. 

I find it weird that you can drag somewhere very far away from the edge of the screen and have it still trigger the menu. Would it be possible to add a prop like `edgeTolerance` where I could specify `40` and only touches that originate 40px from the edge can trigger the menu?

This would definitely prevent accidental menu openings when interacting with my horizontal `ScrollView`

**Comment by Kureev** [comment]
I'm sorry, not sure I got what you mean by this. Why `toleranceX` doesn't work for you? Very far away from the screen?

**Comment by marcshilling** [comment]
@Kureev I'll try to be more clear. `toleranceX` seems to only affect how FAR you have to drag before it triggers the menu, but fails to take into account the origin of the drag. It seems weird to me to have a left side menu that you can drag open with a touch that originates on the right side of the screen. It would be nice to specify that only touches that start on the left can drag open the menu.

Consider a left side menu. I'm imagining a way to set this hypothetical `edgeTolerance` to 40 so that only touches that start within the first 40 pixels from the left side of the screen will be able to trigger the menu. If I originate a touch at x=50 and then try to drag to the right, it would have no effect since I specified it must be within 40.

**Comment by dubert** [comment]
:+1:

**Comment by Kureev** [comment]
@marcshilling I've took a look on it and I can assert that it respects the point when you started your drag. Sorry, that it took more than 1 month for me to check, but if you update the lib to one of the latest versions, you would be able to experience this :+1:
