### ISSUE TITLE
I need to be updated as slide menu is dragged.

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-side-menu#48]
@Kureev, @skevy, have you guys seen Spotify app? As soon as you start dragging the menu, there is a nice animation happen behind the scene. Unfortunately there is no way for us to do this in current version. So I started to update the `onChange` method. So now, as soon as menu gets dragged, onChange method gets called with a value between 0 and 1. Zero means slide menu is completely close, and 1 means that slide menu is opened. 

I will do the PR in few mins.

p.s. I think we should start rewrite the code in `class` way. ~~I really don't like using `setNativeProps`~~.

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by Kureev** [comment]
I'll look on it today again

**Comment by Kureev** [comment]
Should be done with `react-motion` I guess

**Comment by Kureev** [comment]
I took a fresh look on this and this that it would be solved with `Animated` when `0.8.0` gonna be shipped out. I'll keep you posted

**Comment by alinz** [comment]
@Kureev Awesome. Let me know if you need some help! If we can support multiple menus that would be great.

**Comment by Kureev** [comment]
@alinz Thanks for yours efforts! You can always pick up some unsolved issues ;)

**Comment by Kureev** [comment]
In `0.12.1` you can have an access to content view style while dragging. Isn't it enough?

**Comment by alinz** [comment]
It worked! :D Thanks, I love the new `animationFunction`. It did the trick.

```js
animationFunction={(prop, value) {
    if (!this.listener) {
      this.listener = prop.addListener((value) => {
        //this is what I wanted part HEYYYYYY
      });
    }
    return Animated.timing(
      prop,
      {
        toValue: value,
        duration: 300,
      }
    );
  }}
```

If you come to Canada, let me know! :beers: on me!

**Comment by Kureev** [comment]
@alinz haha I'll remember it! ;)
