### ISSUE TITLE
navigator

### ISSUE THREAD

**Issue by digitalhobo** [Kureev/react-native-side-menu#61]
Hi, Thanks for the module, it looks great.

Is their any way of creating a inner shadow to the menu block.
:0)

**Comment by Kureev** [comment]
You mean like this shadow?
![image](https://cloud.githubusercontent.com/assets/2273613/8592007/6452d1b6-262c-11e5-93cc-4e4ba8f8854c.png)
I think it's about styling your content View element. I guess if you add something like box shadow (take a look there http://facebook.github.io/react-native/docs/view.html#style) it'll work. Let me know anyway.

**Comment by digitalhobo** [comment]
Yes, thats exactly the effect.
:0)

**Comment by Kureev** [comment]
@digitalhobo try to add shadow to your main view, that should work

**Comment by dubert** [comment]
That's not working for me.. this is what I get:

(Removing flex: 1)
<img width="487" alt="screen shot 2015-07-14 at 15 07 22" src="https://cloud.githubusercontent.com/assets/1843672/8682280/10f35934-2a3a-11e5-98fb-fc7e3e91b75d.png">
<img width="487" alt="screen shot 2015-07-14 at 15 07 25" src="https://cloud.githubusercontent.com/assets/1843672/8682283/13a73fba-2a3a-11e5-9166-c8ec160edb60.png">

**Comment by piyushchauhan2011** [comment]
:+1:  Not working for me either.

**Comment by Kureev** [comment]
I need to take a look on it more close

**Comment by jsierles** [comment]
This works for me here by setting a shadow  on content area's container view.

https://rnplay.org/apps/OOV7NA

**Comment by Kureev** [comment]
I think that's solved

**Comment by tomkur** [comment]
What was the solution? The link provided by @jsierles does not seem to show anything.

**Comment by ma-pe** [comment]
@tomkur 
did you find a solution?

**Comment by hctangaa** [comment]
@tomkur @ma-pe Did you guys find a solutions? I am facing the same problem right now.

**Comment by ma-pe** [comment]
No I didn't :(
Still accepting this flaw...
