### ISSUE TITLE
New Packager config for accessing react-native internal modules.

### ISSUE THREAD

**Issue by alinz** [Kureev/react-native-side-menu#64]
ok, I think we need to change couple of things and I want to know your (@Kureev) opinion about it. 
based on this ticket, https://github.com/facebook/react-native/issues/1808, we should change some code as follows:

instead of this:

```js
var deviceScreen = require('Dimensions').get('window');
```

we should do it this way

```js
var { Dimensions } = require('react-native');
var deviceScreen = Dimensions.get('window');
```

if you don't do it you will get this annoying error from `packager`.

```bash
Unable to resolve module Dimensions ...
```

what do you think? I really liked the idea of `@providesModule` in comment which makes it a lot easier to find a module. It seems that this feature will be removed. I don't know for sure.

**Comment by alinz** [comment]
I will close this issue since, it's no longer needed. They keep changing it.

**Comment by Kureev** [comment]
Lol, it becomes complicated to close issues before they becomes deprecated :D

**Comment by alinz** [comment]
@Kureev this is not a slide-menu's issue. They keep changing the packager which makes it a lot harder to update my project. Any how, as soon as you are using `Dimensions` inside any projects, you will get packager warning. That warning is just an annoying thing that does nothing. So I think it is safe to ignore it until they fix the packager.

**Comment by Kureev** [comment]
No probs, when it's gonna be stable I'll fix it according confirmed spec

**Comment by piyushchauhan2011** [comment]
:+1:
