### ISSUE TITLE
iPad portrait

### ISSUE THREAD

**Issue by jawadrehman** [Kureev/react-native-side-menu#65]
I am having an issue with an iPad Air in portrait mode. It doesnt take the full height of the screen. 

Have also tested using the example on here.

**Comment by Kureev** [comment]
Have you tried `flex: 1` for your views? Do you have your View stretched correctly without side menu?
To give you more feedback, I need screenshot and version of react-native and plugin you're using.

**Comment by jawadrehman** [comment]
i have react native version 0.6, and the side menu version 0.9.0 .

I am sending pictures of how it looks like by just putting the menu item , or just putting the content. 

flex : 1 is on all these components. 

![img_0006](https://cloud.githubusercontent.com/assets/1839153/8616430/287fefb2-26f3-11e5-87d1-7a865c0b70cc.PNG)
![img_0007](https://cloud.githubusercontent.com/assets/1839153/8616432/28a35952-26f3-11e5-8a01-677c74dd4317.PNG)
![img_0008](https://cloud.githubusercontent.com/assets/1839153/8616431/289eb956-26f3-11e5-8ebf-26ac6c675abd.PNG)

**Comment by jawadrehman** [comment]
@Kureev

**Comment by Kureev** [comment]
Wow, that's really weird, I'll take a look

**Comment by Kureev** [comment]
@alinz fyi, mb you have any thoughts so far?

**Comment by jawadrehman** [comment]
i have found a hackish solution around it. 

i used react-native-device module, and set the height of the container view using the height provided and it seems to work. but it would be really helpful if its sorted out.

**Comment by Kureev** [comment]
so if the issue is in the wrong height of the wrapper element - it's good, I can manage it easily. Thanks for this feedback, it'll scope my research and save my time ;)

**Comment by Kureev** [comment]
@jawadrehman You know, I took a look on implementation, and honestly I don't like it (I mean react-native-device). I prefer that kind of check made on iOS part. There is a nice gist for that https://gist.github.com/Jaybles/1323251 and I think I gonna implement that in the nearest future and plug it in as a dependency for side menu. That would help I guess.

**Comment by jawadrehman** [comment]
but why would you need to set the height, isnt there a way of using flex to
do this ?

**Comment by Kureev** [comment]
because we already use it https://github.com/Kureev/react-native-side-menu/blob/master/styles.js#L10 and it seems not working.

**Comment by Kureev** [comment]
@jawadrehman btw, are you sure your bottom menu haven't any weird paddingTop or something?

**Comment by jawadrehman** [comment]
" width: deviceScreen.width,height: deviceScreen.height, " whats that about
?

**Comment by jawadrehman** [comment]
I have tried the example code, without the tab bar and navbar and it still
has that padding left at the bottom .

**Comment by Kureev** [comment]
Yeah, that's weird. Maybe you're right about `deviceScreen`, until scroll it should works fine, but then it breaks, right?

**Comment by jawadrehman** [comment]
nah, it just has that padding as soon as the screen loads

**Comment by Kureev** [comment]
You know, I tried to run my example on iPad Portrait and wasn't able to reproduce it. I'm running react-native `0.7.1` and react-native-side-menu `0.9.5`. Maybe update to latest version would solve your issue?

**Comment by Kureev** [comment]
@brentvatne

**Comment by Kureev** [comment]
probably the same as #82

**Comment by Kureev** [comment]
Ok, we're not supporting RN0.6 any more, I will reopen you'll be able to experience this with latest version.
