### ISSUE TITLE
Mix side menu contents with main contents together after version 0.8 

### ISSUE THREAD

**Issue by bright-sea** [Kureev/react-native-side-menu#67]
There is an issue after version 0.8( till latest version 0.9.2) which mix side menu contents with main contents together. 

![screen shot 2015-07-09 at 12 29 31 am](https://cloud.githubusercontent.com/assets/2636836/8587954/c019a778-25d1-11e5-80d0-0cdae6e6af5c.png)

![screen shot 2015-07-09 at 12 36 32 am](https://cloud.githubusercontent.com/assets/2636836/8588019/b86311ee-25d2-11e5-9969-e0710353c2c9.png)

This happens when main contents wrapped in a ScrollView. If main contents is a WebView, it is OK.

And this issue happens after version 0.8. version 0.7 without any problem.

Here is my code:

                <SideMenu
                    ref='sideMenu'
                    openMenuOffset={Constants.STYLE.SIDE_MENU_WIDTH}
                    animation={'spring'}
                    disableGestures={true}
                    menu={<ReportMenu report={this.props.report}/>}>

                    <View style={styles.container}>
                        <View style={styles.controlBar}>
                        </View>

                        <ScrollView>
                          
                                        <View key={index}>
                                            <Text> label: {component.label} </Text>
                                            <Text> Type: {component.type} </Text>
                                            <Text> Sheet: {WptService.getSheetById(component.sheetId).name} </Text>
                                        </View>
                        </ScrollView>
                    </View>
                </SideMenu>
  

      var styles = StyleSheet.create({
          container: {
              flex: 1,
          },
          controlBar: {
              flexDirection: 'row',
              backgroundColor: Constants.STYLE.LEVEL1_MENU_BACKGROUND,
          },
          countText: {
              flex: 1,
              flexDirection: 'column'
          },
          webView: {
              flex: 1,
          },
      });

**Comment by bright-sea** [comment]
version 0.7 doesn't work with RN version 0.6 (dependence issue which solve recently after  RN dependency removal in package.json). This issue stopped us from upgrading to RN0.6.

**Comment by Kureev** [comment]
It seems that you're not specifying any backgroundColor for main view. As you know, side menu lies behind content view, so if your content view is transparent, you see what you see. Just add backgroundColor to content view and first your issue should be solved. 

About the second one: fb release updates really fast and breaks backward compatibility, I'm trying to do my best to fix that ASAP. If it's a simple issue, you can try to compose PR, I would be glad to merge it.

**Comment by bright-sea** [comment]
Thanks, @Kureev 

Yes, if I add a background to the main view, it is ok now. But this background setting was not required in version 0.7. If this is the solution, maybe we need add this requirement into document. 

It seems some changes in version 0.8 force this requirement. I personally don't think this is a good solution. I like version 0.7 which works great without setting any background.

Regard to issue "version 0.7 can't work with RN0.6",  you already fixed it by remove dependency of RN directly from package.json. So new version 0.9 works with RN0.6. As we have a solution "Add background for main content" now, we are OK to use Side menu 0.9 with RN0.6.

**Comment by Kureev** [comment]
Closed as outdated
