### ISSUE TITLE
Support React 0.7 and above

### ISSUE THREAD

**Issue by grabbou** [Kureev/react-native-side-menu#68]
As per latest changelog, looks like Dimensions shouldn't be required as a standalone module, but from React package instead, e.g.:
```js
import {Dimensions} from 'react-native';
```
Currently, it prints warnings.

**Comment by piyushchauhan2011** [comment]
```
Unable to resolve module Dimensions from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-side-menu/index.js
Unable to resolve module Dimensions from /Users/kartikeychauhan/Documents/testcodes/react-native-test/HelloTest/node_modules/react-native-side-menu/styles.js
```

:+1:

**Comment by Kureev** [comment]
`v0.9.3` has been released with this fix

**Comment by grabbou** [comment]
Thank you <3

**Comment by Kureev** [comment]
If it works, you can close an issue

**Comment by grabbou** [comment]
Will check in a bit, need to upgrate to React 0.7 again :)

**Comment by Kureev** [comment]
I feel sorry that you need to use prev. versions because of my components :(

**Comment by piyushchauhan2011** [comment]
Doesn't work for me :(

**Comment by Kureev** [comment]
@piyushchauhan2011 Can you provide some more feedback what exactly doesn't work, and which versions you're using?

**Comment by piyushchauhan2011** [comment]
I'm using version 0.7.1 react-native and it says Dimensions.get not an object.

I don't understand what is correct way.

```
var React, {
    StyleSheet,
    Dimensions,
} = require('react-native');
```

OR

```
var { Dimensions, } = require('Dimensions');
var React = require('react-native');
```

OR

```
var { React, Dimensions } = require('react-native');
var {
    StyleSheet,
} = React;
```

**Comment by piyushchauhan2011** [comment]
Still using 0.9.2 version :smile:

**Comment by Kureev** [comment]
AFAIK, `Dimensions` should be included from `react-native` package. That should be fixed in `0.9.2`. Please, let me know if it doesn't work for you, @piyushchauhan2011

**Comment by piyushchauhan2011** [comment]
I'm currently using `0.9.2` version which works fine but `0.9.3` version doesn't work for me.

**Comment by Kureev** [comment]
Can you tell me why? @piyushchauhan2011

**Comment by piyushchauhan2011** [comment]
This is the error i'm getting where `index.js:12` is the file from your repository which have the code for `Dimensions`.
I have tried all the way of inclusion of Dimensions, but can't figure it out.

![screen shot 2015-07-17 at 4 11 58 pm](https://cloud.githubusercontent.com/assets/693487/8741579/93e1ccd4-2c9e-11e5-9af6-6d0b0afb6e92.png)

**Comment by piyushchauhan2011** [comment]
Do you know which is the correct way of requiring dimensions ?

**Comment by Kureev** [comment]
Seems I don't. Will check the changelog and fix it asap

**Comment by piyushchauhan2011** [comment]
I think they are still using the old way of requiring the dimensions.
This is from the master branch.

![screen shot 2015-07-17 at 4 40 10 pm](https://cloud.githubusercontent.com/assets/693487/8741878/9357deda-2ca2-11e5-9596-0be9e06bda9f.png)

**Comment by Kureev** [comment]
I think you can check out `0.9.4`

**Comment by piyushchauhan2011** [comment]
Cool.

**Comment by piyushchauhan2011** [comment]
It says.

![screen shot 2015-07-17 at 5 52 33 pm](https://cloud.githubusercontent.com/assets/693487/8742846/a52bc284-2cac-11e5-9ca9-9c95db14264e.png)

**Comment by Kureev** [comment]
Ah, it doesn't support class variables without flag, right

**Comment by piyushchauhan2011** [comment]
I think you removed the constructor too :smile:

**Comment by Kureev** [comment]
@piyushchauhan2011 constructor isn't necessary to override if you use class variables. But babel supports it only with stage=1 enabled (stage=2 enabled by default). I've changed it back in `0.9.5`. Please, take a look (unable to test it now)

**Comment by piyushchauhan2011** [comment]
Cool I checked the newest version, perfect work :+1: Thanks mate really appreciate it. Saved a lot of hours for me :beer:
Cheers!

**Comment by piyushchauhan2011** [comment]
I also wanted to ask you about how to include testing in a project maybe later, if you have suggestion or links please paste it here :smiley:

**Comment by Kureev** [comment]
I'd like to do it, but now I'm really busy at work, so I don't have that much time for open source. I'm trying to improve it, but step by step. I don't have any proposal now, but I'm open to suggestions.

**Comment by Kureev** [comment]
@grabbou I've tried to change it to require from `react-native`, but for 0.7 it doesn't work. So I'll keep it current way until they would be close to deprecate it.

**Comment by piyushchauhan2011** [comment]
:+1: I think it will change in 0.8 release we have to change it then.

**Comment by grabbou** [comment]
Well, it was working with 0.7.1 yesterday, not sure why there are such differences ;( I am gonna fork it temporarily to see if I can upgrade, will let you know.

**Comment by Kureev** [comment]
@grabbou Sure, you can also check `0.9.3` patch commit, I've tried exactly you proposed in subj and it seems fb still doesn't support it or I've made something wrong :)

**Comment by grabbou** [comment]
Ah yeah, that's true. Thanks!

**Comment by grabbou** [comment]
Ok, I confirm it was false issue. It's not yet there in React 0.7, can we move back to previous version on master? :)

**Comment by Kureev** [comment]
I think we can just create a branch like `react-native@0.8` and agregate all breaking changes etc there, and when it'll be stable, we can just merge it into master

**Comment by Kureev** [comment]
But answering your question, you can be explicit about the version you want to use: `react-native-side-menu@0.9.3`

**Comment by grabbou** [comment]
Yeah, that's what I did. Just worried some bugs / features might be implemented in the meantime :) But maybe it's worth waiting till 0.8/0.9 reaches the npm.
