### ISSUE TITLE
Main content layout doesn't stretch when rotate device

### ISSUE THREAD

**Issue by bright-sea** [Kureev/react-native-side-menu#69]
When we rotate device (for example, rotate iphone left or right), everything will automatically adjust from portrait mode to landscape mode for all react native UI components on ios8 devices. But this feature broken when we add side menu.

Here are some pictures and codes:

![screen shot 2015-07-15 at 9 46 55 pm](https://cloud.githubusercontent.com/assets/2636836/8713801/628ea03a-2b3b-11e5-8b37-e41a525fb6ec.png)
![screen shot 2015-07-15 at 9 47 45 pm](https://cloud.githubusercontent.com/assets/2636836/8713800/628d32c2-2b3b-11e5-9b4d-ad0bed9e0685.png)

![screen shot 2015-07-15 at 9 55 04 pm](https://cloud.githubusercontent.com/assets/2636836/8713945/8ff96c56-2b3d-11e5-8427-e229a25fdd9d.png)

We can see that top SegmentedControl and bottom TabBar all stretched correctly, but center content which wrapped in a SideMenu tag will always keep the portrait mode width (Even we start with landscape mode, it will still use portrait width, this is weird) 

                <SideMenu
                    ref='sideMenu'
                    openMenuOffset={Constants.STYLE.SIDE_MENU_WIDTH}
                    animation={'spring'}
                    disableGestures={true}
                    menu={<ReportMenu report={this.props.report}/>}>

                    <View style={styles.container}>
                             some contents here
                    </View>
                </SideMenu>

But if we remove side menu, everything works great when we rotate device (see background color):

![screen shot 2015-07-15 at 10 01 13 pm](https://cloud.githubusercontent.com/assets/2636836/8713911/3057119a-2b3d-11e5-807c-cfa85305a70e.png)

![screen shot 2015-07-15 at 10 04 56 pm](https://cloud.githubusercontent.com/assets/2636836/8713960/a760c4c0-2b3d-11e5-878c-cf31fc04f3d4.png)

                    <View style={styles.container}>
                             some contents here
                    </View>

Use flex: 1 style doesn't help. Any solution or suggestion?

**Comment by Kureev** [comment]
I need to go deep into it. There are few issues related to this already

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by Kureev** [comment]
The issue is that we need to recalculate layout after orientation has been changed. I found a library which solves this until facebook gonna support it on the "native" level: https://github.com/yamill/react-native-orientation.

**Comment by bright-sea** [comment]
@Kureev Thanks for update!

This issue is very critical for us as this prevent us from deploy our app to production. With this issue, the user experience is really bad.

1. Before facebook support that lib on the native level, any workaround for us? for example, Is it possible to add that lib as a dependence in react-native-side-menu? 

2. I saw all facebook react native component can handle this very well, is it possible ask their team member for help, for example, raise an issue in RN.

**Comment by ryanmcdermott** [comment]
I'm experiencing this bug as well.

**Comment by bright-sea** [comment]
This is an awesome work except this issue. With this issue not been fixed, I don't think this plugin can be used in any  production. 

Will think about remove all dependences of this plugin due to this issue. It's really a hard decision. :(

**Comment by ryanmcdermott** [comment]
For now, I've been locking the orientation which seems to work. You can do this inside your project navigator. If you don't need landscape mode I recommend this until the issue is fixed.
![screen shot 2015-08-20 at 10 31 27 am](https://cloud.githubusercontent.com/assets/5114666/9387558/c2b30738-4726-11e5-8a10-5f2bdeabfecf.png)

**Comment by Kureev** [comment]
I feel myself so sorry for not fixing it for a while. But it's not a critical bug, you can workaround it if you wish: use react-native-orientation library to detect orientation change and re-initialize side-menu, that will work. Basically, I even think that usual re-render will help (but I need to check). The reason why I haven't solved it yet, is that I really don't want to add native Obj-C module dependency. But I think I would, if so many people messed up with it.

**Comment by piyushchauhan2011** [comment]
:+1: @Kureev
