### ISSUE TITLE
Menu from the example works once in a while in IOS device

### ISSUE THREAD

**Issue by pointcom** [Kureev/react-native-side-menu#7]
The menu example seems to work perfectly in the IOS Simulator. But when I try to run it on my device (iPhone 5S), it doesn't work as expected. The menu shows up once in a while.

**Comment by Kureev** [comment]
I'll take a look today on my 5C and let you know :+1:

**Comment by pointcom** [comment]
:+1: Thanks.
Do you need a little video to better understand what's the issue? 
I see the "help wanted" label, So I guess this can help.

**Comment by Kureev** [comment]
It'll be very kind of you

**Comment by pointcom** [comment]
Actually I can repro the issue in the IOS Simulator. (iPhone 6)

Here is the video where you can see the problem : 
https://www.dropbox.com/s/fhh7moifeuvumfq/react-native-side-menu.mov?dl=0

The following line of code seems to be the cause of this issue : 
https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L86

I tried to debug the `x` and `y` values when I swipe horizontally and sometimes `y` has another value than 0. (eg: 1 or 23).

I tried to directly return `true` in the `handleMoveShouldSetPanResponder` function and the problem disappears.

**Comment by Kureev** [comment]
1) https://github.com/Kureev/react-native-side-menu/blob/master/index.js#L86 really looks strange. @chirag04 fyi.
2) I've tried on my 5C, can't reproduce your issue. Do you see it on my example? I'm really curious now.

**Comment by pointcom** [comment]
I use the latest version of `react-native`.

Extract of my `package.json` :
```
  "dependencies": {
    "react-native": "git@github.com:facebook/react-native.git#master"
  },
```

I hope this helps.

**Comment by Kureev** [comment]
Yeah, I bumped my version and I see your problem now. Trying to figure out why we need https://github.com/Kureev/react-native-side-menu/commit/cd7b348a8990ddde8777a22aa79c81f02b675102

**Comment by Kureev** [comment]
@pointcom Should be fixed in 0.2.4

**Comment by pointcom** [comment]
@Kureev Yeah, it works now! Thank you!

**Comment by pointcom** [comment]
@Kureev I think I know why the previous code tested the y axis value. 
I just added a view with a scroll and when I scroll the view with a vertical swipe, sometimes the side menu appears.

**Comment by chirag04** [comment]
@pointcom  thats exactly y i added that y check. But like @Kureev  said we need a better way to do this.

**Comment by Kureev** [comment]
@pointcom @chirag04 Not sure I got it. In my example you can find side view with scroll and it works fine. Could you reproduce your issue on it?

**Comment by pointcom** [comment]
Sorry I wasn't clear enough and my example was wrong.

If you add a `ListView` **inside** the `SideMenu` here : 
https://github.com/Kureev/react-native-side-menu/blob/master/examples/simple/index.ios.js#L44-L55

Then the scroll on this `Listview` would not work.

Because of this commit : eb6c8f4296f358e88de72d0088d64e112386ca30
But if we revert this commit, then my initial issue would come back ('Menu from the example works once in a while in IOS device').

I guess we need to better handle the swipe motion.

**Comment by pointcom** [comment]
I have just created a Pull Request about this issue : 
https://github.com/Kureev/react-native-side-menu/pull/9

Feel free to review it.
