### ISSUE TITLE
Implement fancy animation!

### ISSUE THREAD

**Issue by grabbou** [Kureev/react-native-side-menu#73]
Hey, just finished playing around with the code, and following:

```js
import SideMenu from 'react-native-side-menu';

export default class Menu extends SideMenu {

  updatePosition() {
    var style = {};
    var scaleFactor = this.left > 0
        ? this.left / this.props.scaleFactor / 100
        : 1;
    style.transform = [{
      scale: scaleFactor
    }];
    this.sideMenu.setNativeProps({
      left: this.left,
      style: style
    });
  }

}
```
makes this:
<img width="365" alt="screen shot 2015-07-17 at 14 01 47" src="https://cloud.githubusercontent.com/assets/2464966/8746711/647552e8-2c8c-11e5-98dc-89448fe1db89.png">

DefaultProps:
- scaleFactor - 3
- animationKind - 'slide' (for compatibility)

Can we implement it by exporting a `ScaleMenu` class that will extend `Menu` and override the above method + add two more props described above? Simple.

**Comment by alinz** [comment]
I like the idea. I'd like to see if we can provide some fancy animations and expose a method which let's others override and implement a new animations.

**Comment by grabbou** [comment]
Maybe:
```
updatePosition() {
     var props = this.props.getNativeProps && this.props.getNativeProps({left: this.left, isOpened: this.isOpened});
     this.sideMenu.setNativeProps({
      ...props,
      left: this.left
    });
  }
```

**Comment by Kureev** [comment]
I gonna implement this in master right after `0.8.0` will become stable

**Comment by alinz** [comment]
Agreed, 0.8 still very buggy at the moment. I stopped using it for production. Can't wait for stable release.

**Comment by grabbou** [comment]
It won't change, maybe 0.9 will be better, can you elaborate on that a bit? About to update to 0.8

**Comment by alinz** [comment]
My app is relying on [WebViewBridge](https://github.com/alinz/react-native-webview-bridge) and there is an open issue with react-native 0.7 and above https://github.com/facebook/react-native/issues/2010 which prevents me to upgrade. 

If your app is not using Higher Order Component or WebView, then you should be fine.

**Comment by Kureev** [comment]
In principle, we can try to implement it now with `react-motion` and freeze this version for `react-native` < 0.8. And in 0.8+ we can use `Animated`

**Comment by alinz** [comment]
@Kureev agreed, I really want to get my hands on both libraries. I will try to squeeze my time to implement the simple solution for this and let you know.

**Comment by Kureev** [comment]
Solved in `0.12.1`

**Comment by bkniffler** [comment]
Hey, how would something like @grabbou s work look like with the latest version?

**Comment by grabbou** [comment]
Like ths:
```jsx
<SideMenu
          animationFunction={animationFunction}
          animationStyle={animationStyle}>
    ...
</SideMenu>
```
```js
 const animationStyle = value => {
      return {
        transform: [{
          scale: value.interpolate({
            inputRange: [0, 100],
            outputRange: [1, 0.95]
          })
        }],
        left: value
      };
    };

    const animationFunction = (prop, value) => {
      return Animated.spring(prop, {
        toValue: value,
        friction: 8,
        tension: 50
      });
    };
```

**Comment by bkniffler** [comment]
I absolutely agree that this component could greatly benefit from such examples, especially this one! Thanks for the explanation.

**Comment by Kureev** [comment]
@grabbou can you compose it an example or at least add a block into readme?

**Comment by grabbou** [comment]
Yeah, will add in a new example later today or at leat add a block (have to figure it out)

**Comment by cinder92** [comment]
any update about this theme? 👍

**Comment by NelsonPRSousa** [comment]
Is there any update about this theme?
