### ISSUE TITLE
Disable interactions with right view when menu is open

### ISSUE THREAD

**Issue by grabbou** [Kureev/react-native-side-menu#75]
Should be a matter of setting a prop `disableGesturesWhenMenuOpened` or something + `pointerEvents: none` when isOpen. What do you think?

**Comment by Kureev** [comment]
We have `disableGestures` for that. Check out readme

**Comment by grabbou** [comment]
AFAIK this is for disabling `slide to open` gestures? Anyway, I've managed to sort that out differently.

**Comment by grabbou** [comment]
BTW - are there any plans to make this menu props driven? I'd like to manage `isOpen` with Flux and the following mods are nearly making it possible:
```js
class MyMenu extends SideMenu {
  constructor(props) {
    super(props);
    this.isOpen = this.props.isOpen;
  }

  componentWillReceiveProps(props) {
    super.componentWillReceiveProps(props);
    if (this.props.isOpen !== props.isOpen) {
      this.toggleMenu();
    }
  }
}
```
The only exception is it does not respect initial state - when isOpen equals to true. I think the solution is to call `updatePosition` in constructor when isOpen is true?

**Comment by Kureev** [comment]
I like this idea, that's definitely a step forward. But before implementing new functionality we need to fix existing bugs...

**Comment by grabbou** [comment]
If there are some bits where I can help that would be awesome. We highly depend on your component in few of my projects at company as well as in @este community.

**Comment by Kureev** [comment]
@grabbou There are 2 issues I really want to solve asap:
- https://github.com/Kureev/react-native-side-menu/issues/61
- https://github.com/Kureev/react-native-side-menu/issues/65

After that I think we can try to consider the way to improve component
