### ISSUE TITLE
Navigation : undefined is not a function

### ISSUE THREAD

**Issue by tnguyen42** [Kureev/react-native-side-menu#77]
Hi,
Very good job with this menu! I have a problem though...
It's probably me, but I can't find out how to create a navigation that works. By following your example, I just filled the blanks in navigator.push with a title and another component containing a simple View.
Doing this, I keep having the same mistake:
"undefined is not a function (evaluating this.props.navigator.push({title: 'Homepage', component: Homepage})') "

Could you please help me out?
Am I supposed to add a Navigator somewhere?

**Comment by alinz** [comment]
@tnguyen42 I think by mistake you filed an issue in a wrong repo. Probably, you wanted to post on [react-native-nabar](https://github.com/Kureev/react-native-navbar) instead, (I might be wrong though)

For answering your problem, I have couple of thoughts,

First, are you passing `navigator` object as prop to your component inside `rednerScene` method?

Second, To me react-native-navbar is just helper Component to customize the navbar, make sure that you are targeting React Native's `Navigator` object. You might add the ref to your `NavigationBar` and trying to execute methods there.

**Comment by tnguyen42** [comment]
Hi,
Thanks for your answer, but I'm actually talking about the side-menu, Usage Example. In it, it seems there's not Navigator component, which I find weird, considering navigator.push is being called.

Am I supposed to replace <ContentView/> by a Navigator? Or am I supposed to wrap the rendered SideMenu under a Navigator through the renderScene method?

Thanks for your time!

**Comment by alinz** [comment]
Oh I see, This is just an example of how you can pass `navigator` or any other props to menu to interact with your app. You **do not** need that!

So now my question is, do you want to use `Navigator` component as your Side menu's content?

**Comment by tnguyen42** [comment]
For now I don't, but I plan to use a Navigator as my main content and then, navigate thanks to this side-menu.
So I'm wondering what the best pratice should be: replace the ContentView component (from the example) by a Navigator which renders some content like this:
      <SideMenu menu={menu}>
        <Navigator initialRoute, renderScene, etc>
      </SideMenu>

Or wrap everything, including the SideMenu, in a Navigator.
The first one seems more intuitive to me since I don't want the SideMenu to reload everytime...

Cheers!

**Comment by tnguyen42** [comment]
Your component looks very good rt2zz, I'm gonna try it, thanks!

**Comment by Kureev** [comment]
I think it's worth to make a component which will aggregate navbar, side-menu and describe relations between :)
