### ISSUE TITLE
Some weird error about navigation.

### ISSUE THREAD

**Issue by piyushchauhan2011** [Kureev/react-native-side-menu#78]
![screen shot 2015-07-24 at 6 46 42 pm](https://cloud.githubusercontent.com/assets/693487/8870846/6478fd96-3234-11e5-8bba-00815c630354.png)

@Kureev @alinz

**Comment by alinz** [comment]
@piyushchauhan2011 We need a little bit more info, like a sample code. I've seen this error showing up when one animation layout try to interrupt and execute while another is in progress.

**Comment by piyushchauhan2011** [comment]
I just updated my version to react-native 0.8.0 release and this error no longer exist, everything works perfectly :+1: @Kureev @alinz
