### ISSUE TITLE
Disable/enable Side Menu 

### ISSUE THREAD

**Issue by InnovatingBliss** [Kureev/react-native-side-menu#79]
Scenario:

I'm using the side menu to open a view for filtering a list. The **Filters Component** is the "menu" and the **Master Component** is a table inside a navigator. After selecting an item in my table, the **Detail Component** is pushed onscreen. At this point, I'd like to disable the side-menu since filters are no longer needed.

I attempted this to no avail: 

    	this.refs.sideMenu.disableGestures = true;

Thoughts?

@Kureev

**Comment by Kureev** [comment]
In theory, if you don't have explicit button for opening menu, that would be enough, but doesn't looks to me as a "perfect solution". I think I need to expose something like `disable()` method.

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by InnovatingBliss** [comment]
> this.refs.sideMenu.disableGestures = true;

So, I figured out this didn't work. I wasn't triggering a state update. I had to have that property linked to a flag I called `filterDisabled`.

    lockMenu() {
		this.setState({
			filterDisabled: true
		});
	}

And then adding this: 
    
      <SideMenu disableGestures={this.state.filterDisabled} ... >

**Comment by piyushchauhan2011** [comment]
Cool @InnovatingBliss
