### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by marclundgren** [Kureev/react-native-side-menu#8]
1. npm install
2. npm start
3. attempt to build the example

![screen shot 2015-04-30 at 8 15 20 am](https://cloud.githubusercontent.com/assets/1154834/7414609/1cc82abe-ef11-11e4-955d-9cb3d5285c20.png)

**Comment by Kureev** [comment]
Hi @marclundgren! Just tried to reproduce your issue, but unfortunately(or fortunately?) unsuccessfully. Please, provide output of the `npm list --depth=0` command and try to restart xcode.

**Comment by marclundgren** [comment]
hi @Kureev :)
```
react-native-side-menu [master] npm list --depth=0
react-native-side-menu@0.2.4 /Users/marc/Dev/react-native-side-menu
└── react-native@0.4.1
```

**Comment by Kureev** [comment]
what about react-native itself?
```bash
simple@0.0.1 /Users/xamd/Projects/react-native-side-menu/examples/simple
├── react-native@0.4.1
└── react-native-side-menu@0.2.4
```

**Comment by marclundgren** [comment]
okay. it looks like I only `npm install`ed from the root repo. I didn't realize there was another `package.json` in `examples/simple`.

**Comment by Kureev** [comment]
No probs! Let me know if you'll need any further help

**Comment by marclundgren** [comment]
I'm interested in learning how to create a `react-native-accordian-list`. I am trying to extract knowledge from the use of your `animations.js` code :)

**Comment by marclundgren** [comment]
Accordion for reference: http://jqueryui.com/accordion/

**Comment by Kureev** [comment]
https://facebook.github.io/react/docs/animation.html I got all my knowledges from here: https://facebook.github.io/react/docs/animation.html
