### ISSUE TITLE
view height not responsive to acture high

### ISSUE THREAD

**Issue by leoabacade** [Kureev/react-native-side-menu#82]
I am using SideMenu with TabBarIOS
The code is like below:

```javascript
<SideMenu
            menu={<Test />}
            touchToClose={this.state.touchToClose}
            onChange={this.handleChange.bind(this)}>
          
                <TabBarIOS selectedTab={this.state.selectedTab} style={styles.container2}>
                    <TabBarIOS.Item
                        title="Schedule"
                        selected={this.state.selectedTab === 'schedule'}
                        icon={ require('image!schedule') }
                        onPress={() => {
                            this.setState({
                                selectedTab: 'schedule'
                            });
                        }}>
                    <Schedule this_weeks_bookings={this.props.responseData.this_weeks_bookings} navigator={this.props.navigator}/>    
                    </TabBarIOS.Item>
                    
                    <TabBarIOS.Item
                        title="Messages"
                        selected={this.state.selectedTab === 'messages'}
                        icon={ require('image!messages') }
                        onPress={() => {
                            this.setState({
                                selectedTab: 'messages'
                            });
                        }}>
                    <Messages/>    
                    </TabBarIOS.Item>

                    <TabBarIOS.Item
                        title= "Profile"
                        selected={this.state.selectedTab === 'profile'}

                        icon={ require('image!profile') }
                        onPress={() => {
                            this.setState({
                                selectedTab: 'profile'
                            })
                        }}>
                    <Profile responseData = {this.props.responseData}/>    
                    </TabBarIOS.Item>
                    
                </TabBarIOS> 
</SideMenu>
```

## But the page hight seems to be effect by Personal Hotspot Notification in Statusbar

![img_1844](https://cloud.githubusercontent.com/assets/2664504/9132162/0cd5e90a-3d24-11e5-8ee4-44eee9171295.PNG )
## (texts below icons disappeared)
![img_1846](https://cloud.githubusercontent.com/assets/2664504/9132164/0d26db94-3d24-11e5-8fa9-81f59bbd34b3.PNG )

## when I remove the ```<SideMenu>```, the page hight is correct like below (texts below icons appeared):

![img_1849](https://cloud.githubusercontent.com/assets/2664504/9132184/3362b896-3d24-11e5-9260-e8bc60b8f0af.PNG )

## when I keep ```<SideMenu>``` but hiding the StatusBar ( Status bar is initially hidden in Plist ), the page hight is also correct like below (texts below icons appeared):
![img_1850](https://cloud.githubusercontent.com/assets/2664504/9132510/9a546200-3d26-11e5-95d9-baad3ad81063.PNG)

**Comment by Kureev** [comment]
@brentvatne

**Comment by kocyigityunus** [comment]
this bug is not about your code. the react application at the core must listen for UIApplicationWillChangeStatusBarFrameNotification and UIApplicationDidChangeStatusBarFrameNotification notifications. then relayout all the components in the application, means re render everything. this is also a problem for ios 9 split screen feature too.

**Comment by kocyigityunus** [comment]
i tried it on a sample application i wrote and react core handles 40px status bar. i think your problem is about using screen height. style it again and dont use dimension.screen.height and you are done.

**Comment by leoabacade** [comment]
@kocyigityunus , I don't use dimension.screen.height in the style, could you give an example where I might fine this variable?

**Comment by Kureev** [comment]
I can't reproduce it. Can you please make an example project with this bug. 
I would be glad to help you with this.

**Comment by Kureev** [comment]
Closed due to feedback with code example
