### ISSUE TITLE
how would i toggle this sidebar from another component

### ISSUE THREAD

**Issue by miknonny** [Kureev/react-native-side-menu#84]
Please gies How would i toggle the sidebar from another component when  it is clicked or onPress or something ?

**Comment by Kureev** [comment]
There are so many ways to do it... If you're using flux - you can emit an action and listen for it in the menu component, then toggle menu by `this.props.menuActions.toggle()`. Also you can pass `menuActions` thru the stack of your views or add them into context of your view tree...

The general idea is to use `menuActions` which you can reach as a props at `menu` or `content` elements.

**Comment by miknonny** [comment]
Thanks a lot!
