### ISSUE TITLE
Animation Slide Out / Snapping Back

### ISSUE THREAD

**Issue by kkjdaniel** [Kureev/react-native-side-menu#89]
Hello,

I have this issue, when trying to slide out the menu it seems to refuse when giving it a gentle pull and attempts to snap back, if on the other hand I drag it all the way across the screen quickly it pops open. I believe it could be styling related but I'm not sure, is there a way to smooth this out?

![](https://i.gyazo.com/6d48a7d2929c32e351f47d2c01f8e32d.gif)

Thanks for your help!

**Comment by Kureev** [comment]
Can you provide some info about `react-native` version you're using and `react-native-side-menu` version?

**Comment by kkjdaniel** [comment]
Issue was solved in the end, there was an event being used to monitor the viewport size which was causing a problem, unrelated to the plugin.
