### ISSUE TITLE
Not issue, but question

### ISSUE THREAD

**Issue by sjanahan** [Kureev/react-native-side-menu#91]
Hi Kureev,

I am attempting to make a Tinder type react application with react native side view and https://github.com/brentvatne/react-native-animated-demo-tinder.

I went and disabledGestures on the side menu because it can be confusing as to whether one is swiping right to say no to a card or to pull out the side menu.

I am attempting to place a button in charge of pulling out the side menu but I am not having much luck.

I have my repo here:
https://github.com/sjanahan/Quotail

https://github.com/sjanahan/Quotail/blob/master/MainScreen.js#L154

The above link is where I am attempting to place a button that will call ToggleMenu, but I am not seeing the toggleMenu function exposed on the SideMenu?

Pleas let me know what I am not understanding here fundamentally.

Best,
Janahan

**Comment by Kureev** [comment]
`menuActions` is a property which is exposed to all first-level components in the tree (e.g. content first-level components). It contains API for side-menu you want. Take a look on README

**Comment by sjanahan** [comment]
Thank you for getting back to me.

I posted that question on perhaps day 3 of starting out with react native.

I now have child components closing the side menu when necessary.

Awesome contribution!

- Janahan

**Comment by sjanahan** [comment]
I didn't really understand at the time that render isn't returning
an instance but rather a skeleton of what should be instantiated
when the time is right.

Also, I didn't understand the idea of passing properties down from
parent to child in a one way fashion.

Thank you again.

-Janahan

**Comment by Kureev** [comment]
I glad you found a solution for your issue. Sorry for late response :octopus:
