### ISSUE TITLE
[Examples] When menu is open, interactions with content should be disabled

### ISSUE THREAD

**Issue by grabbou** [Kureev/react-native-side-menu#93]
And should cause menu to hide.

Like here:
https://github.com/este/native/blob/feature/new-react-new-flux/src/app/app.react.js#L122-L130

And implementation:
https://github.com/este/native/blob/feature/new-react-new-flux/src/components/contentView.react.js

What do you think?

In my case, I needed to change one thing in component by itself to allow it to be props driven:
https://github.com/este/native/blob/feature/new-react-new-flux/src/components/menu.react.js#L16-L20

Thanks to that, I can now keep the state of menu in state and easily toggle it w/o referring to it.

**Comment by grabbou** [comment]
I think this can be easily added as another example :)

**Comment by Kureev** [comment]
Maybe I misunderstood your question, but it seems you describing functionality which is already there: take a look on `touchToClose` option

**Comment by grabbou** [comment]
Maybe I just missed recent development updates, will take a look now!

**Comment by grabbou** [comment]
Yep, works like a charm!

**Comment by grabbou** [comment]
Anyway, what do you think about the second part of my question - implementing the `componentWillReceiveProps` in order to allow passing a prop `isOpen` instead of calling a method on `this.refs.menu.toggleMenu()` ?

**Comment by Kureev** [comment]
You mean to set a default state of the menu?

**Comment by grabbou** [comment]
Yes, but also would be cool for menu to respect that state when props change, e.g. keeping `isMenuOpen` in a store (Redux for instance) and changing that state with action from different components, instead of calling `this.refs.menu` manually.

Obviously, I can write that sugar in my `componentWillReceiveProps` top-level component manually, but I think it's a nice small addition.
