### ISSUE TITLE
How to deal with another pan responder inside <ContentView />

### ISSUE THREAD

**Issue by michaltaberski** [Kureev/react-native-side-menu#94]
Hello,

I would like to ask for advise how to deal with second pan responder I need to use inside ContentView?

I would like to keep nice pannable/swipeable character of the menu, but inside Content View I still need to have pan responder gestures.

The final resoult I would like to achive is:

![ip](https://cloud.githubusercontent.com/assets/202033/9626103/684ac80a-515b-11e5-925e-290dd1bbf8d9.png)

__How should I approach it?__

### // EDIT

or even nicer solution would be to have:

![ip2](https://cloud.githubusercontent.com/assets/202033/9627733/474f2b68-5166-11e5-8be1-b1e6eb3e5403.png)

**Comment by Kureev** [comment]
I think both of those behaviors are possible with this plugin. Do you have any error when you try to implement it?

**Comment by michaltaberski** [comment]
So my idea was to merge both functionalities:

1) the side menu
2) this tinder like animation
https://github.com/brentvatne/react-native-animated-demo-tinder

In the end what I got is:
http://screencast.com/t/0zU3s82piuq

It looks like the gestures are interfering each other, so I would like to know if there is a pattern to solve this kind of issues.

**Comment by Kureev** [comment]
I think if I would expose `onStartShouldSetResponderCapture` it'll solve the issue, right? You would be able to specify custom function and ignore your panResponder gestures. Am I right?

**Comment by michaltaberski** [comment]
I think it might help.

The solution I'm thinking about is following:

I could write custom `onStartShouldSetResponderCapture` function, where I check if the swipe starts on another component with panResponder (return `false`), or if it starts just on background (return `true`)

Does it make sense for you?

**Comment by Kureev** [comment]
That's exactly what I mean in the comment above :) I consider this as a good improvement, will try to implement it ASAP

**Comment by michaltaberski** [comment]
Awesome, thx.

**Comment by Kureev** [comment]
Exposed in `0.13.0`
