### ISSUE TITLE
Can't redirect from side menu

### ISSUE THREAD

**Issue by kstrack-grose** [Kureev/react-native-side-menu#97]
Hi,
Since navigator isn't a part of the side menu's props, we can't redirect from links on the side menu. This makes it hard to do a lot of functionality you would expect from a side menu (logout, go to settings, etc). Are we missing something?

**Comment by alinz** [comment]
React and React-Native's component should do one thing and one thing good. What you have to do is using something like [redux](https://github.com/rackt/redux)  or [reflux](https://github.com/reflux/refluxjs). 

I have been using `react-native-side-menu` along side of `redux` which provides me complete control by generating actions. 

So for a simple example, let say that you have a logout on side-menu and you want to call something, what you have to do is, generate a `logout` action which can be routed to proper logic some where else. 

For using redux, you can look at [template project](https://github.com/alinz/example-react-native-redux)

If you need an specific example, let me know and I will create a simple example using redux and side-menu

**Comment by kstrack-grose** [comment]
Okay, that makes sense. Thank you.

**Comment by mikedizon** [comment]
@alinz if you could create that example using side-menu and redux, it would be hugely appreciated.

This is the issue I've run into.

https://github.com/Kureev/react-native-side-menu/issues/105

**Comment by alinz** [comment]
@mikedizon I have found a small time and created a simple project. You can look at it and see how I control Side Menu with Redux. if you need any help just create an issue under that project. 

Here's the link to example:

[example-side-menu-redux](https://github.com/alinz/example-side-menu-redux)

Cheers

**Comment by mikedizon** [comment]
@alinz thank u so much

**Comment by Kureev** [comment]
@alinz <3
