### ISSUE TITLE
How to open side-menu from another component

### ISSUE THREAD

**Issue by dannytce** [Kureev/react-native-side-menu#99]
As `menuActions` are passed through props to `menu` component, I can't use them in another components. For example, I'd like to open side-menu by click on leftButton in NavigatorIOS, but have no idea how.

Thanks in advance.

**Comment by Kureev** [comment]
Solved in `0.14.0`. Check the [release notes](https://github.com/Kureev/react-native-side-menu/releases/tag/v0.14.0).
